---
abstract: 'DNS extension language'
author:
  - 'John Levine <extlang@m.jl.ly>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.112621'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-DNS-Extlang
no_index:
  directory:
    - t
    - inc
requires:
  Net::DNS: 1.11
  perl: 5.006
version: 0.2
